In [4]:
import numpy as np

In [19]:
a = np.zeros((0,3), dtype=np.float64)

In [28]:
a = np.vstack((a, [1, 2, 3]))

In [33]:
a[7]

IndexError: index 7 is out of bounds for axis 0 with size 4

In [40]:
b = np.arange(15).reshape(5, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [38]:
np.mean(b, 0)

array([6., 7., 8.])

In [41]:
np.mean(b, 1)

array([ 1.,  4.,  7., 10., 13.])

In [45]:
None or [2]

[2]